DC = docker compose
STORAGES_FILE = docker_compose/storages.yaml
EXEC = docker exec -it
DB_CONTAINER = example-db
LOGS = docker logs
ENV_FILE = --env-file .env




.PHONY: storages
storages:
	${DC} -f ${STORAGES_FILE} ${ENV_FILE} up -d

.PHONY: storages-down
storages-down:
	${DC} -f ${STORAGES_FILE} down 

.PHONY: storages-down-volumes
storages-down-volumes:
	${DC} -f ${STORAGES_FILE} down --volumes

.PHONY: storages-logs
storages-logs:
	${LOGS} ${DB_CONTAINER} -f

