# Generated by Django 5.0.6 on 2024-06-08 19:08

from django.db import (
    models,
    migrations,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Токен пользователя')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Токен пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
