# Generated by Django 5.0.6 on 2024-06-09 12:10

import uuid

from django.db import (
    models,
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('9855c1b1-2436-4b0f-ad95-588f5b28312d'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
