# Generated by Django 5.0.6 on 2024-06-17 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('7b15bc48-37e4-4520-900b-516cff4ab7c1'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
