# Generated by Django 5.0.6 on 2024-06-17 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('dac004dd-520d-47ba-a0b1-30d230cae11a'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
