# Generated by Django 5.0.6 on 2024-06-17 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('c06e041b-c0aa-47e3-bb48-5200968cda7a'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
