# Generated by Django 5.0.6 on 2024-06-20 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('5c2488d1-1149-4ed6-91f8-cec560722a2a'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
