# Generated by Django 5.0.6 on 2024-06-20 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('4376838a-821d-4130-9005-f92ba0f9f943'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
