# Generated by Django 5.0.6 on 2024-06-20 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('52a876a6-b430-4a6c-8500-fea1d57f43d3'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
