# Generated by Django 5.0.6 on 2024-06-20 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('6b9f06cb-9c42-46a3-995c-0e31ed237e4e'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
