# Generated by Django 5.0.6 on 2024-06-20 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('a73b61a3-ce46-453d-84ce-bb4982f9327e'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
