# Generated by Django 5.0.6 on 2024-06-20 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('178dfdc4-87f5-453c-847b-b81c5ede8fcb'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
