# Generated by Django 5.0.6 on 2024-06-20 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('adb4ec59-e62c-4c51-a963-daf071bd07fb'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
