# Generated by Django 5.0.6 on 2024-06-20 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('ea29af2c-6009-450d-b7f9-06feb892b095'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
