# Generated by Django 5.0.6 on 2024-06-20 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('37e77c11-be20-4891-b70d-10929ad11c81'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
