# Generated by Django 5.0.6 on 2024-06-20 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('7202a0b6-1b62-4396-a513-dc8f1690deb5'), max_length=255, unique=True, verbose_name='Токен пользователя'),
        ),
    ]
