# Generated by Django 5.0.6 on 2024-06-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=64, verbose_name='Название интенсива')),
                ('color', models.CharField(max_length=7, verbose_name='Цвет интенсива')),
            ],
            options={
                'verbose_name': 'Интенсив',
                'verbose_name_plural': 'Интенсивы',
            },
        ),
    ]
