# Generated by Django 5.0.6 on 2024-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intensive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение интенсива'),
        ),
    ]
