# Generated by Django 5.0.6 on 2024-06-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intensives', '0002_intensive_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intensive',
            old_name='image',
            new_name='image_url',
        ),
    ]
