# Generated by Django 5.0.6 on 2024-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensives', '0003_rename_image_intensive_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intensive',
            name='image_url',
        ),
        migrations.AddField(
            model_name='intensive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='intensives/', verbose_name='Изображение интенсива'),
        ),
    ]
