# Generated by Django 5.0.6 on 2024-06-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensives', '0004_remove_intensive_image_url_intensive_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('duration', models.PositiveIntegerField()),
                ('intensive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intensives.intensive')),
            ],
            options={
                'verbose_name': 'Сессия интенсива',
                'verbose_name_plural': 'Сессии интенсивов',
            },
        ),
    ]
